# Max. amount of gold to own for inviting a player.
max_grant_adviser: 7

# Translations used by this plugin.
messages:
    wait_for_mod: 'Bitte etwas Geduld. Ein Moderator wird sich um deine Freischaltung kuemmern.'
    no_mod_online: 'Derzeit ist kein Moderator online. Du wurdest auf die Warteliste gesetzt. Bitte etwas Geduld...'
    rules_already_accepted: 'Du hast die Regeln bereits akzeptiert!'
    only_one_adviser: 'Du kannst nur eine Person angeben, von welcher du eingeladen wurdest.'
    invalid_usage_invited_by_command: 'Du musst einen gueltigen Spielernamen uebergeben!'
    too_late_to_set_adviser: 'Du wurdest bereits freigeschalten. Es ist zu spaet jemanden anzugeben.'
    thanks_to_advice1: 'Danke, dass du einen neuen Spieler angeworben hast.'
    thanks_to_advice2: 'Du bekommst %d Goldbarren!'
    adviser_do_not_exist: 'Der Spieler exestiert nicht! Bitte den exakten Spielernamen eingeben.'
    not_accepted_rules: 'Spieler hat die Regeln noch nicht akzeptiert!'
    player_unlocked: 'Spieler wurde freigeschalten. Vergiss nicht mit /promote <user> den Spieler auch den passenden Rang zu geben!'
    unlocked: 'Du wurdest freigeschalten! Viel Spass auf unserem Server.'
    players_to_unlock: 'Es sind neue Spieler zum Freischalten verfuegbar.'
    can_not_invited_by_yourself: 'Du kannst nicht von dir selbst eingeladen worden sein!'
    adviser_recognized: 'Der Spieler wird benachrichtigt.'